### PR TITLE
Project overview

### PR DESCRIPTION
**Pull request by Eleonore9**
status:
* New UI for project overview and map
* New UI for table header only
* Get all features data from Overpass XML  via a JSON file on S3
* Data retrieved on the frontend, parsed and displayed using DataTables
* Get data from modified campaign.json (for summary stats at the top)
* Re-style dataTable
status-28nov_2

### CODE REVIEW

**Comment by russbiggs** [comment]
When ```campaign_contributors``` is an empty list it's showing ```[]```
Screen Shot 2019-11-28 at 2 25 12 PM


This should be a number

**Comment by russbiggs** [comment]
theres a lot of code that doesnt seem to be used particularly in the lambda_functions/render/feature/ directory.  

* unnecessary print statements in ```lambda_functions/render/feature/aws.py```
* list method isn't used anywhere in ```lambda_functions/render/feature/aws.py```
* unused changes in ```lambda_functions/render/feature/utilities.py``` e.g ```create_feature_details_json```

**Comment by Eleonore9** [comment]
> When `campaign_contributors` is an empty list it's showing `[]`
> Screen Shot 2019-11-28 at 2 25 12 PM
> 
> This should be a number

When you had me look for the key `"campaign_contributors"` instead of `"contributors"` in `campaign.json` I thought you meant that the key for the total number of contributors would be renamed `"campaign_contributors"` in a separate PR. My bad!

**Comment by Eleonore9** [comment]
OK, modifications done!

**Comment by Eleonore9** [comment]
I've also rebased with `develop` so that should solve the merge conflict

**Pull request merged**
