### PR TITLE
Add vector tiles generation

### PR DESCRIPTION
**Pull request by willemarcel**
add lambda function to generate vector tiles from the campaing geojson files and update map.html to load the vector tiles. Solves https://github.com/hotosm/MapCampaigner/issues/683

### CODE REVIEW

**Comment by willemarcel** [comment]
I generated vector tiles and uploaded new `map.html` files to the staging campaings:
* 9386a612e0b64909875f3e30a22fe123
* 54c0d74ebac94303a2b540aa9d82b00d

How to test:

Fetch the pull request, update the `app_config` to `AWSStagingConfig` and run the server

Issues we need to solve:

* The map is not loading with the right width and height, so you need to resize the window to start interacting with the map. I think it's a problem caused by how the `map.html` is inserted on the `campaign_detail.html`. I'll try to include the map.html on it, instead of loading from S3. I believe there is not necessity to upload the map.html to the S3 anymore.

**Comment by willemarcel** [comment]
I realized the `map.html` needs to be rendered and upload to S3 yet, as the campaign page can have more than one map.

I fixed the map rendering issues. So after the review, it's ready to be merged.

**Comment by JorgeMartinezG** [comment]
I do not have any issues with this approach, just aquick question @willemarcel .

Are the geojson files kept within the folder in s3? When this PR is merged, it will break the Maps.me button, because all the data points that are used to create the .kml file is read from leaflet client. The issue will be solved reading directly from s3.

**Comment by willemarcel** [comment]
@JorgeMartinezG Yes, the geojson files will continue to be stored on S3.

Maybe the best approach would be to modify the `generate_kml` view to receive just the campaign uuid and type and get the geojson from the S3. The geojson data is split on more than one file if the campaign returned too much data, in that case we would need to merge it before converting to kml.

**Comment by JorgeMartinezG** [comment]
Exactly. I was thinking about the same approach

**Pull request merged**
