### PR TITLE
Landing Page With New Design (& Build Step)

### LINKED ISSUE #717: Create landing page
Home Page

### PR DESCRIPTION
**Pull request by localjo**
This PR resolves #717 

* Adds a webpack config and build process to enable asset bundles, SASS and ES6
* Adds a webpack dev server that enables live reloading of assets in development
* Adds some npm scripts for convenience
* Adds template based on new design with new styles for header and footer
* Creates landing page, learn page and styleguide page

To run this branch you need Node/npm installed, then from the project root run `npm install` and `npm run build` and run the app as normal.

To start the front end dev server, after running the app as normal, you can run `npm run start`, and access the app at the URL displayed by that command. The webpack dev server will watch assets for changes and reload the app in the browser automatically when assets change.

This PR also adds two shortcuts that work on mac without a need to manually activate the Python venv first:

`npm run start:server` starts the Flask app, equivalent to `python flask_project/runserver.py`

`npm run deploy:lambda` deploys Lambda functions, equivalent to `python ./.travis/deploy_lambda_functions.py`

### CODE REVIEW

**Comment by localjo** [comment]
@russbiggs This is ready for review. If you already have this branch locally, you'll need to delete it and check it out again, because I rebased it on develop.

I adjusted the Travis configuration, so that works fine now, but we may need to make some other adjustments for any other build/deploy environments.

**Comment by localjo** [comment]
I've made some changes to this branch:

I updated the styles to match the HOT styleguide. I was looking at the design in Figma and missed the details that were only in Zeplin.

For the header margins, I changed some CSS so that the margins are 16px for large (desktop) viewports. Because the layout is responsive, at widths lower than 991px the margin is automatically calculated to fill available space and might not be exactly 16px.

I moved the inline styles that @Eleonore9 mentioned to the stylesheets.

I'm cautious about the use of `!important` in the stylesheets, but I think [it's a good choice in this case](https://css-tricks.com/when-using-important-is-the-right-choice/), since I'm writing utility classes and overriding the Bootstrap utility classes. Basically, it allows the buttons to be re-used in different contexts without their styles being changed unintentionally by their parents.

I agree that the JavaScript at the end of base.html could be extracted to a separate file. It's at the bottom of the file in the existing template. I tried to move it to the main.js bundle, but that created some JavaScript errors on other pages, so I think that optimization will take more effort to solve. For now, I opted to stick with the existing pattern and we can come back to it later.

I'll update the URL for the "My Projects" link in #752 since that's where I'm making modifications to that route.

I also updated the `/styleguide` page to show all of the re-usable components that have been used so far in the redesign so we can see them on one page. That will make it easier to re-use those components as we build the other pages, and to eliminate unused CSS once the redesign is complete.

**Comment by russbiggs** [comment]
Oops, in commit 781e58b you removed the contact link.  In my review I meant removing this:

Screen Shot 2019-11-06 at 7 36 32 AM

and bring this back:

```html
 <a class="pull-left" href="https://www.hotosm.org/contact">Made by HOTOSM Community. Get in touch.</a>
```

**Comment by localjo** [comment]
@russbiggs Oops, sorry about that. Fixed.

**Pull request merged**
