### PR TITLE
Download kml file for Maps.me

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
The Maps.me button is not working because the function that is executed when this button is pressed was removed on this commit 17789b1f00ea91e6e8220be446162160a720f687

I present in this Pull request a similar approach, using the following tasks:
- When the button is pressed, I fetch data points from leaflet map.
- Then, an ajax request is performed to the _/generate_kml_ handler that parses the json file with data points and creates a kml, which is saved within the CACHE_DIR path.
- If the request is successfull, the server returns the url for the file to be downloaded.
- I also created a alert-success div on the page but I hid it. Just in case, we can show it after successful request.

I also show a screen recording in my mobile device:
http://recordit.co/Xb3a2o9WbF

**Note.** The _generate_kml_ handler works only with Points type. I don't know if it was a requirement.

### CODE REVIEW

**Comment by pierrealixt** [comment]
@JorgeMartinezG I see you're working directly from your `develop` branch. 
I will advise you to create a feature branch (or a [topic branch](https://git-scm.com/book/en/v1/Git-Branching-Branching-Workflows) `fix-download-kml` for example and keep your local `develop` branch always up to date to the remote branch. 
Following this, it becomes easier to work on more than one feature.

**Comment by smit1678** [comment]
@JorgeMartinezG Awesome, and thanks for including the screencast to be able to see the interaction. One question - does it download all the point data? I haven't looked further into certain cases but do we expect issues if the downloaded file includes thousands of points? Not sure if that is or will be an issue. 

> **Note.** The _generate_kml_ handler works only with Points type. I don't know if it was a requirement.

I think that's correct because I think that's all that Maps.me can handle.

**Comment by JorgeMartinezG** [comment]
@pierrealixt Thanks for your suggestion. I will create a new PR using a new branch instead of develop. @smit1678 Yes, right now, the data is collected from the Leaflet map, which is created from multiple requests to the S3 bucket. We can limit the size of the kml files when the number of points is really high.

**Comment by smit1678** [comment]
@JorgeMartinezG Ok great, let's push this then and then run a few tests to see when we run into issues.

**Pull request merged**
